services:
  fastgpt-dify-adapter:
    container_name: fastgpt-dify-adapter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    image: registry.cn-guangzhou.aliyuncs.com/kangarooking/fastgpt-dify-adapter:1.0.2
    env_file:
      - .env
    restart: unless-stopped
